
version: "3"

services:
  #Database service
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: oli_woo
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql

  #Wordpress (image based on Apache)
  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: dev
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: oli_woo
    volumes:
      ["./:/var/www/html"]

volumes:
  mysql: {}
