
version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: bluePiggy
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql

